# do not edit this file. This file was automatically generated by format-test.lisp
from clformat import clformat
def test():
    """ 
>>> clformat("| ~{~<|~%| ~,33:;~2d ~>~}|", [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
|  0  1  2  3  4  5  6  7  8  9 |
| 10 11 12 13 14 15 16 17 18 19 |
| 20 21 22 23 24 25 26 27 28 29 |
| 30 31 32 33 34 35 36 37 38 39 |
| 40 41 42 43 44 45 46 47 48 49 |
| 50 51 52 53 54 55 56 57 58 59 |
| 60 61 62 63 64 65 66 67 68 69 |
| 70 71 72 73 74 75 76 77 78 79 |
| 80 81 82 83 84 85 86 87 88 89 |
| 90 91 92 93 94 95 96 97 98 99 |
>>> clformat("~5t~a ~15t~a ~25t~a~%", "cat", "cat", "iPhone")
     cat       cat       iPhone

>>> clformat("~5t~a ~15t~a ~25t~a~%", "thunder", "iPhone", "lightning")
     thunder   iPhone    lightning

>>> clformat("~5t~a ~15t~a ~25t~a~%", "stipulate", "thunder", "pattern")
     stipulate  thunder  pattern

>>> clformat("~5t~a ~15t~a ~25t~a~%", "iPhone", "stipulate", "iPhone")
     iPhone    stipulate  iPhone

>>> clformat("~30<~a~;~a~;~a~>~%", "pattern", "thunder", "cat")
pattern      thunder       cat

>>> clformat("~30<~a~;~a~;~a~>~%", "pattern", "iPhone", "pattern")
pattern     iPhone     pattern

>>> clformat("~30<~a~;~a~;~a~>~%", "iPhone", "stipulate", "thunder")
iPhone    stipulate    thunder

>>> clformat("~30<~a~;~a~;~a~>~%", "stipulate", "iPhone", "rain")
stipulate     iPhone      rain

>>> clformat("~30<~a~;~a~;~a~>~%", "lightning", "pattern", "pattern")
lightning   pattern    pattern

>>> clformat("~30<~a~;~a~;~a~>~%", "rain", "cat", "pattern")
rain        cat        pattern

>>> clformat("~30<~a~;~a~;~a~>~%", "iPhone", "thunder", "rain")
iPhone      thunder       rain

>>> clformat("~30<~a~;~a~;~a~>~%", "cat", "cat", "iPhone")
cat         cat         iPhone

>>> clformat("~30<~a~;~a~;~a~>~%", "cat", "pattern", "iPhone")
cat       pattern       iPhone

>>> clformat("~30<~a~;~a~;~a~>~%", "stipulate", "lightning", "cat")
stipulate    lightning     cat

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "iPhone", "thunder", "rain")
   iPhone   
  thunder   
    rain    

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "cat", "iPhone", "lightning")
    cat     
   iPhone   
 lightning  

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "cat", "cat", "pattern")
    cat     
    cat     
  pattern   

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "cat", "rain", "cat")
    cat     
    rain    
    cat     

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "thunder", "rain", "thunder")
  thunder   
    rain    
  thunder   

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "lightning", "thunder", "rain")
 lightning  
  thunder   
    rain    

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "cat", "iPhone", "rain")
    cat     
   iPhone   
    rain    

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "cat", "pattern", "thunder")
    cat     
  pattern   
  thunder   

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "thunder", "thunder", "iPhone")
  thunder   
  thunder   
   iPhone   

>>> clformat("~12:@<~a~>~%~12:@<~a~>~%~12:@<~a~>~%", "cat", "thunder", "lightning")
    cat     
  thunder   
 lightning  

    """ 